### ISSUE TITLE
Issue with Navigation bar

### ISSUE THREAD

**Issue by 4d4r5h** [Infinito-IIT-Patna/Infinito2020#14]
List items of Navigation bar are visible only when hovered upon.

![Screenshot (1)](https://user-images.githubusercontent.com/46349391/103105780-f5817a80-4655-11eb-9d2f-94939a9d0e85.png)

**Comment by StrixROX** [comment]
That only happens when the db is not setup. After setting up the db it works fine.
![image](https://user-images.githubusercontent.com/40167899/103134549-ecd18880-46d7-11eb-92e9-581a1224ad38.png)
![image](https://user-images.githubusercontent.com/40167899/103134552-f22ed300-46d7-11eb-9af2-ad68d3970393.png)

**Comment by StrixROX** [comment]
However there are two navbars in the site. We need to make a common navbar and replace it on all pages. Please change the issue description to accommodate this.
1.
![image](https://user-images.githubusercontent.com/40167899/103134597-518ce300-46d8-11eb-8eae-3e0e5e8238fd.png)


2.
![image](https://user-images.githubusercontent.com/40167899/103134599-5baee180-46d8-11eb-9c4d-f0335c69c657.png)

**Comment by debarghya472** [comment]
Those are actually not required
